require('dotenv').config({ path: './server/.env' })
const express = require('express')
const app = express()
const cors = require('cors')
const auth_router = require('./routes/authRoute')
const companyRoute = require('./routes/companyRoute')
const stationRoute = require('./routes/stationRoute')
const tripRoute = require('./routes/tripRoute')
const stopOverRoute = require('./routes/stopOverRoute')
const bookingRoute = require('./routes/bookingRoute')
const invoiceRouter = require('./routes/invoiceRoute')
const userRouter = require('./routes/userRoute')
const authenticateToken =
  require('./controllers/authController').authenticateToken
app.use(cors())
app.use(express.json())

app.use('/auth', auth_router)
app.use('/admin', stationRoute)
app.use('/admin', companyRoute)
app.use(tripRoute)
app.use('/admin', stopOverRoute)
app.use(bookingRoute)
app.use(invoiceRouter)
app.use(userRouter)

app.listen(3000, () => console.log('server start'))
